{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.bind9_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% do c1.set_user(values.run_as.user, values.run_as.group) %}

{% do c1.environment.add_user_envs(values.bind9.additional_envs) %}

{% do c1.add_caps(["SETUID", "SETGID", "SYS_NICE", "NET_ADMIN"]) %}

{% do c1.healthcheck.set_custom_test("dig -x 127.0.0.1 @127.0.0.1 > /dev/null") %}

{% do c1.add_port(values.network.udp_port) %}
{% do c1.add_port(values.network.tcp_port) %}
{% do c1.add_port(values.network.rndc_port) %}

{% do c1.add_storage("/etc/bind", values.storage.config) %}
{% do perm_container.add_or_skip_action("config", values.storage.config, perms_config) %}

{% do c1.add_storage("/var/log", values.storage.logs) %}
{% do perm_container.add_or_skip_action("logs", values.storage.logs, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{{ tpl.render() | tojson }}
